---
- name: Metabase Container on a previusly installed Docker
  hosts: all
  become: true
  become_user: root
  vars:
    docker_network_name: posgres_metabase

  tasks:
    - name: Pull Metabase  Docker Image
      docker_image:
        name: metabase/metabase:latest
        source: pull
        tag: latest

    - name: Create a network
      docker_network:
        name: "{{ docker_network_name }}"

    - name: Create postgres
      docker_container:
        name: postgres
        image: postgres:latest
        hostname: postgres
        env:
          POSTGRES_USER: "metabase"
          POSTGRES_DB: "metabaseappdb"
          POSTGRES_PASSWORD: "abc1234"
        state: started
        networks:
          - name: "{{ docker_network_name }}"


    - name: Create Metabase Container
      docker_container:
        name: metabase
        image: metabase/metabase:latest
        env:
          MB_DB_TYPE: "postgres"
          MB_DB_DBNAME: "metabaseappdb"
          MB_DB_PORT: "5432"
          MB_DB_USER: "metabase"
          MB_DB_PASS: "abc1234"
          MB_DB_HOST: "postgres"
        state: started
        ports:
          - 3001:3000
        networks:
          - name: "{{ docker_network_name }}"



