- hosts: myhosts
  become: True
  become_user: root
  vars:
    grafana_admin_password: "abc1234"
  tasks:
    - name: update system
      ansible.builtin.apt:
        name: "*"
        state: latest
    - name: Import Grafana GPG signing key [Debian/Ubuntu]
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        state: present
        validate_certs: false
      register: _add_apt_key
      until: _add_apt_key is succeeded
      retries: 5
      delay: 2

    - name: Add Grafana repository [Debian/Ubuntu]
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        update_cache: true
      register: _update_apt_cache
      until: _update_apt_cache is succeeded
      retries: 5
      delay: 2

    - name: Install Grafana
      package:
        name: "grafana"
        state: "latest"
      register: _install_packages
      until: _install_packages is succeeded
      retries: 5
      delay: 2
    - name: start service grafana-server
      systemd:
        name: grafana-server
        state: started
        enabled: yes
    - name: wait for service up
      uri:
        url: "http://127.0.0.1:3000"
        status_code: 200
      register: __result
      until: __result.status == 200
      retries: 120
      delay: 1
    - name: change admin password for grafana gui
      shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
      register: __command_admin
      changed_when: __command_admin.rc !=0
