 - hosts: myhosts
   become: True
   become_user: root

   tasks:
    - name: Create Netplan configuration for enp3s0 interface with DHCP
      copy:
        dest: "/etc/netplan/00-dhcp-config.yaml"
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              enp3s0:
                dhcp4: true
        owner: root
        group: root
        mode: '0600'

    - name: Apply Netplan configuration
      command: netplan apply
      become: true

