services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: "metabase"
      POSTGRES_DB: "metabaseappdb"
      POSTGRES_PASSWORD: "abc1234"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network      

  metabase:
    image: metabase/metabase
    container_name: metabase
    environment:
      MB_DB_TYPE: "postgres"
      MB_DB_DBNAME: "metabaseappdb"
      MB_DB_PORT: "5432"
      MB_DB_USER: "metabase"
      MB_DB_PASS: "abc1234"
      MB_DB_HOST: "postgres"
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    networks:
      - my-network
      
volumes:
  postgres_data:

networks:
  my-network:
    name: proba_objetiboa
    external: true
    driver: bridge    
